version: "3.9"

services:
  app:
    build: .
    container_name: airline_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: flights
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: airline_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flights
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 10
